# Generated by Django 5.1.7 on 2025-04-22 02:55

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Einfach'), ('medium', 'Mittel'), ('hard', 'Schwierig')], max_length=10)),
                ('recipe_img', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='images/recipes/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(to='recipe_ingredients.recipeingredient')),
            ],
        ),
    ]
