# Generated by Django 5.1.7 on 2025-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen'), ('snacks', 'Snacks')], default='snacks', max_length=15),
            preserve_default=False,
        ),
    ]
