# Generated by Django 5.1.7 on 2026-01-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_category_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portion',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
