# Generated by Django 5.1.7 on 2026-01-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorite',
        ),
    ]
