# Generated by Django 5.1.7 on 2025-03-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipe_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('ingredient', 'amount')},
        ),
    ]
