# Generated by Django 5.1.7 on 2026-01-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listcollection', '0002_alter_listcollection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='listcollection.listcollection')),
            ],
        ),
    ]
