# Generated by Django 5.1.7 on 2025-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lockout_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
