# Generated by Django 5.1.7 on 2025-10-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcollection',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
