# Generated by Django 5.1.7 on 2025-10-09 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcollection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcollection',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
