# Generated by Django 5.1.7 on 2026-01-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_favorite_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
    ]
