# Generated by Django 5.1.7 on 2026-01-16 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_remove_favorite_is_favorite'),
        ('recipe', '0006_remove_recipe_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'recipe'], name='favorites_f_user_id_2ac2bf_idx'),
        ),
    ]
